In [11]:
import os
os.chdir(r"C:\Users\ryanh\code\projects\ytrec")

In [17]:
RAW = "data/processed/ve_channels/ve_with_features.json"
df = pd.read_json(RAW)

In [18]:
df.head()

,channel_id,channel_name,title,description,country,topics,keywords,uploads,videos
0,UCqgh7QNlVV8kv3LBTJZYWrg,The Film Essay,The Film Essay,A video essay channel devoted to making videos...,GB,[https://en.wikipedia.org/wiki/Television_prog...,"""film essay"" ""video essay"" ""film analysis"" ""fi...",UUqgh7QNlVV8kv3LBTJZYWrg,[{'title': 'Why Christopher Nolan uses time as...
1,UCjFqcJQXGZ6T6sxyFB-5i6A,Every Frame a Painting,Every Frame a Painting,Taylor & Tony are gone again! Thanks for watch...,None,[https://en.wikipedia.org/wiki/Lifestyle_(soci...,"filmmaking ""film analysis"" ""video essay""",UUjFqcJQXGZ6T6sxyFB-5i6A,[{'title': 'Every Frame x Lackadaisy - Intervi...
2,UCr8r7UVsDaRiIQSVUHVBd_A,Nikki Carreon,Nikki Carreon,"Hello!! Just here making silly stuff, making s...",US,[https://en.wikipedia.org/wiki/Lifestyle_(soci...,None,UUr8r7UVsDaRiIQSVUHVBd_A,"[{'title': 'Why I Went to a MENTAL HOSPITAL.',..."
3,UCjKSoJlPgcK6BmoSqXpj5xQ,Action Button,Action Button,patreon.com/actionbutton\ntwitch.tv/actionbutt...,None,[https://en.wikipedia.org/wiki/Role-playing_vi...,None,UUjKSoJlPgcK6BmoSqXpj5xQ,"[{'title': 'ACTION BUTTON PICTURES PRESENTS ""L..."
4,UCUyvQV2JsICeLZP4c_h40kA,Thomas Flight,Thomas Flight,"Exploring the artistry behind cinema, TV, and ...",None,"[https://en.wikipedia.org/wiki/Entertainment, ...","movies film ""video essays"" ""film essay""",UUUyvQV2JsICeLZP4c_h40kA,"[{'title': 'Why Some Movies Feel More Alive', ..."

In [20]:
df.shape

(251, 9)

In [21]:
OUT = "data/preprocessed/channels_pp.csv"
df_out = pd.read_csv(OUT)

In [23]:
df_out.head()

,channel_id,channel_name,country,text
0,UCqgh7QNlVV8kv3LBTJZYWrg,The Film Essay,NaN,A video essay channel devoted to making videos...
1,UCjFqcJQXGZ6T6sxyFB-5i6A,Every Frame a Painting,NaN,Taylor & Tony are gone again! Thanks for watch...
2,UCr8r7UVsDaRiIQSVUHVBd_A,Nikki Carreon,NaN,"Hello!! Just here making silly stuff, making s..."
3,UCjKSoJlPgcK6BmoSqXpj5xQ,Action Button,NaN,patreon.com/actionbutton\ntwitch.tv/actionbutt...
4,UCUyvQV2JsICeLZP4c_h40kA,Thomas Flight,NaN,"Exploring the artistry behind cinema, TV, and ..."