In [8]:
from pathlib import Path
import pandas as pd

In [9]:
base = Path.cwd()
base

WindowsPath('c:/Users/ryanh/code/projects/ytrec/notebooks')

In [10]:
data = base.parent / "data" / "processed" / "channels_pp.csv"
df = pd.read_csv(data)

In [13]:
df.shape
df.head()

,channel_id,channel_name,description,topics,keywords,videos
0,UCqgh7QNlVV8kv3LBTJZYWrg,The Film Essay,A video essay channel devoted to making videos...,"Television program, Film, Entertainment",film essay video essay film analysis film revi...,Why Christopher Nolan uses time as architectur...
1,UCjFqcJQXGZ6T6sxyFB-5i6A,Every Frame a Painting,Taylor & Tony are gone again! Thanks for watch...,"Lifestyle (sociology), Entertainment, Film",filmmaking film analysis video essay,Every Frame x Lackadaisy - Interview with Trac...
2,UCr8r7UVsDaRiIQSVUHVBd_A,Nikki Carreon,"Hello!! Just here making silly stuff, making s...","Lifestyle (sociology), Entertainment, Film","Lifestyle (sociology), Entertainment, Film",Why I Went to a MENTAL HOSPITAL. Stranger Thin...
3,UCjKSoJlPgcK6BmoSqXpj5xQ,Action Button,patreon.com/actionbutton\ntwitch.tv/actionbutt...,"Role-playing video game, Action-adventure game...","Role-playing video game, Action-adventure game...","ACTION BUTTON PICTURES PRESENTS ""LOS ANGELES N..."
4,UCUyvQV2JsICeLZP4c_h40kA,Thomas Flight,"Exploring the artistry behind cinema, TV, and ...","Entertainment, Film, Lifestyle (sociology)",movies film video essays film essay,Why Some Movies Feel More Alive Top 10 Films o...

results for mentour pilot

In [18]:
df[df["channel_name"] == "The Sin Squad"]

,channel_id,channel_name,description,topics,keywords,videos
184,UCNpkJ9sQUkmXoFrXBwi7XxA,The Sin Squad,The Sin Squad: Looking too closely at (mostly ...,"Lifestyle (sociology), Entertainment, Film",animation reviews animation analysis media ana...,The Frozen 2 Soundtrack is Worse Than You Thin...

In [19]:
df[df["channel_name"] == "I Finished A Video Game"]

,channel_id,channel_name,description,topics,keywords,videos
106,UCVdDUN69YsAXPxh2y71sMtQ,I Finished A Video Game,Extremely detailed videos about the beautiful ...,"Action game, Role-playing video game, Video ga...","Action game, Role-playing video game, Video ga...",Live Roasting The Half Life Video (and talking...

In [20]:
df[df["channel_name"] == "Cartoonshi シ"]

,channel_id,channel_name,description,topics,keywords,videos
231,UCkaP2qh7t1Dc6LNzytNrf9g,Cartoonshi シ,I live off of hot chocolate and I might hate e...,"Television program, Entertainment, Film","Television program, Entertainment, Film",The END of Smiling Friends... Will Toy Story 5...

In [21]:
df[df["channel_name"] == "LEMMiNO"]

,channel_id,channel_name,description,topics,keywords,videos
143,UCRcgy6GzDeccI7dkbbBna3Q,LEMMiNO,Long-form videos about space and mysteries and...,documentary documentaries mysteries mystery vi...,documentary documentaries mysteries mystery vi...,Shouting at Stars: A History of Interstellar M...

In [22]:
df[df["channel_name"] == "pey talks anime"]

,channel_id,channel_name,description,topics,keywords,videos
217,UCvjaYSxQ9DLQBSrurmhEjiQ,pey talks anime,For business inquires email peytalks@gmail.com...,"Film, Entertainment","Film, Entertainment",When motive and identity collide Frieren's sec...

In [23]:
df.columns

Index(['channel_id', 'channel_name', 'description', 'topics', 'keywords',
       'videos'],
      dtype='object')