In [2]:
from pathlib import Path
import pandas as pd
base = Path.cwd()
data = base.parent.parent / "data" / "processed" / "channels_pp.csv"
df = pd.read_csv(data)

In [3]:
df.head()

,channel_id,channel_name,description,topics,keywords,videos
0,UCqgh7QNlVV8kv3LBTJZYWrg,The Film Essay,A video essay channel devoted to making videos...,"Television program, Film, Entertainment",film essay video essay film analysis film revi...,Why Christopher Nolan uses time as architectur...
1,UCjFqcJQXGZ6T6sxyFB-5i6A,Every Frame a Painting,Taylor & Tony are gone again! Thanks for watch...,"Lifestyle (sociology), Entertainment, Film",filmmaking film analysis video essay,Every Frame x Lackadaisy - Interview with Trac...
2,UCr8r7UVsDaRiIQSVUHVBd_A,Nikki Carreon,"Hello!! Just here making silly stuff, making s...","Lifestyle (sociology), Entertainment, Film","Lifestyle (sociology), Entertainment, Film",Why I Went to a MENTAL HOSPITAL. Stranger Thin...
3,UCjKSoJlPgcK6BmoSqXpj5xQ,Action Button,patreon.com/actionbutton\ntwitch.tv/actionbutt...,"Role-playing video game, Action-adventure game...","Role-playing video game, Action-adventure game...","ACTION BUTTON PICTURES PRESENTS ""LOS ANGELES N..."
4,UCUyvQV2JsICeLZP4c_h40kA,Thomas Flight,"Exploring the artistry behind cinema, TV, and ...","Entertainment, Film, Lifestyle (sociology)",movies film video essays film essay,Why Some Movies Feel More Alive Top 10 Films o...

In [5]:
# imputing (manually Doug Woolever because many missing data)
df.loc[df["channel_name"] == "Doug Woolever", "description"] = "One day when I was watching Spongebob, I noticed something bizarre. This thing was so bizarre that I decided to spend months analyzing every single episode of Spongebob Squarepants in search of answers. What I ended up finding was a completely original and impossibly well-supported conspiracy theory that will destroy everything we have ever been told about Bikini Bottom. The world needs to know the truth. This is the video that will change everything. Watch at your own risk. This video was created for commentary/analysis and to generate discussion through the presentation of research, protected under fair use."
df.loc[df["channel_name"] == "Doug Woolever", "topics"] = "Entertainment"
df.loc[df["channel_name"] == "Doug Woolever", "keywords"]  = "TV analysis theory spongebob"

In [ ]:
# dropping channels
# CHANNELS_TO_DROP = ["Philosophy Corner", "Psyphos"]
# df = df[~df["channel_name"].isin(CHANNELS_TO_DROP)]

In [8]:
# making sure channels dropped
df.loc[df["channel_name"] == "Psyphos"]

Empty DataFrame
Columns: [channel_id, channel_name, description, topics, keywords, videos]
Index: []